// This file is automatically generated
using System;

namespace MSHealthCloudApi.Net.Model
{
    public enum ActivityType
    {
        Unknown,
        Custom,
        CustomExercise,
        CustomComposite,
        Run,
        Sleep,
        FreePlay,
        GuidedWorkout,
        Bike,
        Golf,
        RegularExercise
    }
}