// This file is automatically generated
using System;

namespace MSHealthCloudApi.Net.Model
{
    public enum DeviceFamily
    {
        Unknown,
        Band,
        Windows,
        Android,
        IOS
    }
}