// This file is automatically generated
using System;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MSHealthCloudApi.Net.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class ErrorResponse
    {
        [JsonPropertyAttribute("error")]
        public ErrorInformation Error { get; set; }

    }
}