// This file is automatically generated
using System;

namespace MSHealthCloudApi.Net.Model
{
    public enum MapPointType
    {
        Unknown,
        Start,
        End,
        Split,
        Waypoint
    }
}