// This file is automatically generated
using System;

namespace MSHealthCloudApi.Net.Model
{
    public enum Period
    {
        Unknown,
        Activity,
        Minute,
        QuarterHourly,
        HalfHourly,
        Hourly,
        Daily,
        Weekly,
        Last30Days,
        CalendarMonth,
        Last90Days,
        CalendarYear,
        Last365Days,
        Segment
    }
}