// This file is automatically generated
using System;

namespace MSHealthCloudApi.Net.Model
{
    public enum SegmentType
    {
        Unknown,
        Run,
        FreePlay,
        Doze,
        Sleep,
        Snooze,
        Awake,
        GuidedWorkout,
        Bike,
        Pause,
        Resume,
        DistanceBasedInterval,
        TimeBasedInterval,
        GolfHole,
        GolfShot,
        NotWorn
    }
}