// This file is automatically generated
using System;

namespace MSHealthCloudApi.Net.Model
{
    public enum SleepType
    {
        Unknown,
        UndifferentiatedSleep,
        RestlessSleep,
        RestfulSleep
    }
}